<!DOCTYPE html>
<html lang="pt">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.2.1/material.indigo-pink.min.css">
    <script defer src="https://code.getmdl.io/1.2.1/material.min.js"></script>

    <meta property="og:title"       content="Pagamento,Negócios => Seguro ">
    <meta property="og:description" content="Com jabakule , ganhas dinheiros, e faça pagmentos on-line, intermediações de negócios e muito mais... sem ter um cartão Visa, suporte Tel:(+244)923696938">
    <meta property="og:image"       content="<?=$this->urlcaminho?>assets1/img/capa1.png">
    <meta property="og:url"         content="https://www.jabakule.com">
    <meta property="og:type"        content="website">

    <meta property="og:url"                content="https://www.jabakule.com" />
    <meta property="og:type"               content="article" />
    <meta property="og:title"              content="Pagamento Seguro" />
    <meta property="og:description"        content="Com jabakule, ganhas dinheiros, e faça pagmentos on-line, intermediações de negocios e muito mais... sem ter um cartão Visa, suporte Tel:(+244)923696938" />
    <meta property="og:image"              content="<?=$this->urlcaminho?>assets1/img/capa.png" />
    <meta name="google-site-verification" content="jEXlyoI5Jdodkakc_KawvnAib6SlLwxHYrrfOoBQC1A" />



    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title><?=$this->presentacao['empresa'] ?? ''?></title>
    <meta name="description" content="Com jabakulé, ganhas dinheiros, e faça pagamentos on-line, intermediações de negócios e muito mais... sem ter um cartão Visa, suporte Tel:(+244)923696938">
    <meta content="" name="<?=$this->presentacao['empresa'] ?? ''?> <?=$this->presentacao['marca'] ?? ''?>">
    <meta content="" name="<?=$this->presentacao['empresa'] ?? ''?> <?=$this->presentacao['marca'] ?? ''?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <!-- Favicons -->
  <link href="<?=$this->urlcaminho?>assets1/img/<?=$this->presentacao['logotipo'] ?? ''?>" rel="icon">
  <link href="<?=$this->urlcaminho?>assets1/img/<?=$this->presentacao['logotipo'] ?? ''?>" rel="apple-touch-icon">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="generator" content="Mobirise v5.4.1, mobirise.com">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    <link rel="shortcut icon" href="<?=$this->urlcaminho?>/assets3/images/certo.gif" type="image/x-icon">
    <meta name="description" content="">


    <link rel="stylesheet" href="<?=$this->urlcaminho?>/assets3/web/assets/mobirise-icons2/mobirise2.css">
    <link rel="stylesheet" href="<?=$this->urlcaminho?>/assets3/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?=$this->urlcaminho?>/assets3/bootstrap/css/bootstrap-grid.min.css">
    <link rel="stylesheet" href="<?=$this->urlcaminho?>/assets3/bootstrap/css/bootstrap-reboot.min.css">
    <link rel="stylesheet" href="<?=$this->urlcaminho?>/assets3/web/assets/gdpr-plugin/gdpr-styles.css">
    <link rel="stylesheet" href="<?=$this->urlcaminho?>/assets3/animatecss/animate.css">
    <link rel="stylesheet" href="<?=$this->urlcaminho?>/assets3/dropdown/css/style.css">
    <link rel="stylesheet" href="<?=$this->urlcaminho?>/assets3/socicon/css/styles.css">
    <link rel="stylesheet" href="<?=$this->urlcaminho?>/assets3/theme/css/style.css">
    <link rel="preload" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i&display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'">
    <noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i&display=swap"></noscript>
    <link rel="preload" href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i&display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'">
    <noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i&display=swap"></noscript>
    <link rel="preload" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'">
    <noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap"></noscript>
    <link rel="preload" as="style" href="<?=$this->urlcaminho?>/assets3/mobirise/css/mbr-additional.css">
    <link rel="stylesheet" href="<?=$this->urlcaminho?>/assets3/mobirise/css/mbr-additional.css" type="text/css">

    <link rel="stylesheet" href="<?=$this->urlcaminho?>/assets3/css/Bold-BS4-CSS-Image-Slider.css">
    <link rel="stylesheet" href="<?=$this->urlcaminho?>/assets3/css/responsive-blog-card-slider.css">
    <link rel="stylesheet" href="<?=$this->urlcaminho?>/assets3/css/Slider-laptop-1.css">
    <link rel="stylesheet" href="<?=$this->urlcaminho?>/assets3/css/Slider-laptop.css">
    <link rel="stylesheet" href="<?=$this->urlcaminho?>/assets3/css/add.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css">
    <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/v4-shims.js"></script>

    <script>
        $('nav-link').onC
        function menuActive(id){
        localStorage.setItem("idMenu",id);
        }
        let idMenu = localStorage.getItem("idMenu");
        document.getElementById(idMenu).classList.add("active");
    </script>
</head>


<body style="overflow: visible;" >
<div id="corpo" >
<?= $this->content() ?>
</div>

 <!-- script -->
    <script src="<?=$this->urlcaminho?>/assets3/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="<?=$this->urlcaminho?>/assets3/smoothscroll/smooth-scroll.js"></script>
    <script src="<?=$this->urlcaminho?>/assets3/ytplayer/index.js"></script>
    <script src="<?=$this->urlcaminho?>/assets3/dropdown/js/navbar-dropdown.js"></script>
    <script src="<?=$this->urlcaminho?>/assets3/theme/js/script.js"></script>

    <script src="<?=$this->urlcaminho?>/assets3/js/responsive-blog-card-slider-1.js"></script>
    <script src="<?=$this->urlcaminho?>/assets3/js/responsive-blog-card-slider.js"></script>
    <script src="<?=$this->urlcaminho?>/assets3/js/Slider-laptop.js"></script>
    <!-- Google Analytics -->
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-XXXXX-Y', 'auto');
ga('send', 'pageview');
</script>
<!-- End Google Analytics -->

    <div id="scrollToTop" class="scrollToTop mbr-arrow-up"><a style="text-align: center;"><i class="mbr-arrow-up-icon mbr-arrow-up-icon-cm cm-icon cm-icon-smallarrow-up"></i></a></div>
    <input name="animation" type="hidden">
</body>
</html>
