<!DOCTYPE html>
<html lang="pt">

<head>
    <!-- Site made with Mobirise Website Builder v5.5.2, https://mobirise.com -->

    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">

    <link href="/public/assets1/img/<?= $this->presentacao['logotipo'] ?? '' ?>" rel="icon">
    <link href="/public/assets1/img/<?= $this->presentacao['logotipo'] ?? '' ?>" rel="apple-touch-icon">
    <link rel="shortcut icon" href="<?= $this->urlcaminho ?>/assets3/images/logo-com-bordas-brancas-128x139-1.png" type="image/x-icon">

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.2.1/material.indigo-pink.min.css">
    <script defer src="https://code.getmdl.io/1.2.1/material.min.js"></script>

    <!-- Primary Meta Tags -->
<title>Jabakulé, Cartões Virtuais: Visa-jabakule,MasterCard-jabakule, PayPal-jabakule, marketing de Sms</title>
<meta name="title" content="Angola, Cartões Virtuais: Visa-jabakule,MasterCard-jabakule, PayPal-jabakule, marketing de Sms">
<meta name="description" content="Pagementos Online , Cartões virtual em Angonla, moeda jaba, Com jabakulé, ganhas dinheiros, e faça pagamentos online, intermediações de negócios e muito mais... sem ter um cartão Visa, suporte Contacto:(+244)923696938">

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:url" content="http://jabakule.com/">
<meta property="og:title" content="Angola, Cartões Virtuais: Visa-jabakule,MasterCard-jabakule, PayPal-jabakule, marketing de Sms">
<meta property="og:description" content="Pagementos Online , Cartões virtual em Angonla, moeda jaba, Com jabakulé, ganhas dinheiros, e faça pagamentos online, intermediações de negócios e muito mais... sem ter um cartão Visa, suporte Contacto:(+244)923696938">
<meta property="og:image" content="/public/assets/img/capa_jaba.png">

<!-- Twitter -->
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:url" content="http://jabakule.com/">
<meta property="twitter:title" content="Angola, Cartões Virtuais: Visa-jabakule,MasterCard-jabakule, PayPal-jabakule, marketing de Sms">
<meta property="twitter:description" content="Pagementos Online , Cartões virtual em Angonla, moeda jaba, Com jabakulé, ganhas dinheiros, e faça pagamentos online, intermediações de negócios e muito mais... sem ter um cartão Visa, suporte Contacto:(+244)923696938">
<meta property="twitter:image" content="/public/assets/img/capa_jaba.png">

    <meta name="google-site-verification" content="jEXlyoI5Jdodkakc_KawvnAib6SlLwxHYrrfOoBQC1A" />

    <link rel="shortcut icon" href="<?= $this->urlcaminho ?>/assets3/images/certo.gif" type="image/x-icon">
    <link rel="stylesheet" href="<?= $this->urlcaminho ?>/assets3/web/assets/mobirise-icons2/mobirise2.css">
    <link rel="stylesheet" href="<?= $this->urlcaminho ?>/assets3/web/assets/mobirise-icons/mobirise-icons.css">
    <link rel="stylesheet" href="<?= $this->urlcaminho ?>/assets3/web/assets/mobirise-icons-bold/mobirise-icons-bold.css">
    <link rel="stylesheet" href="<?= $this->urlcaminho ?>/assets3/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?= $this->urlcaminho ?>/assets3/bootstrap/css/bootstrap-grid.min.css">
    <link rel="stylesheet" href="<?= $this->urlcaminho ?>/assets3/bootstrap/css/bootstrap-reboot.min.css">
    <link rel="stylesheet" href="<?= $this->urlcaminho ?>/assets3/web/assets/gdpr-plugin/gdpr-styles.css">
    <link rel="stylesheet" href="<?= $this->urlcaminho ?>/assets3/animatecss/animate.css">
    <link rel="stylesheet" href="<?= $this->urlcaminho ?>/assets3/dropdown/css/style.css">
    <link rel="stylesheet" href="<?= $this->urlcaminho ?>/assets3/socicon/css/styles.css">
    <link rel="stylesheet" href="<?= $this->urlcaminho ?>/assets3/theme/css/style.css">
    <link rel="stylesheet" href="<?= $this->urlcaminho ?>/assets3/css/add.css">

    <link rel="preload" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i&display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'">
    <noscript>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i&display=swap">
    </noscript>
    <link rel="preload" href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i&display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'">
    <noscript>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i&display=swap">
    </noscript>
    <link rel="preload" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'">
    <noscript>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap">
    </noscript>
    <link rel="preload" as="style" href="<?= $this->urlcaminho ?>/assets3/mobirise/css/mbr-additional.css">
    <link rel="stylesheet" href="<?= $this->urlcaminho ?>/assets3/mobirise/css/mbr-additional.css" type="text/css">

    <script>
        $('nav-link').onC
        function menuActive(id) {
            localStorage.setItem("idMenu", id);
        }
        let idMenu = localStorage.getItem("idMenu");
        document.getElementById(idMenu).classList.add("active");
    </script>
</head>
<body style="overflow: visible;">
    <div id="corpo">

        <?= $this->content() ?>

    </div>

    <!-- script -->
    <script src="<?= $this->urlcaminho ?>/assets3/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="<?= $this->urlcaminho ?>/assets3/smoothscroll/smooth-scroll.js"></script>
    <script src="<?= $this->urlcaminho ?>/assets3/ytplayer/index.js"></script>
    <script src="<?= $this->urlcaminho ?>/assets3/dropdown/js/navbar-dropdown.js"></script>
    <script src="<?= $this->urlcaminho ?>/assets3/theme/js/script.js"></script>
    <script src="<?= $this->urlcaminho ?>/assets1/js/solicita_cartao.js"></script>

    <link rel="stylesheet" href="<?= $this->urlcaminho ?>/assets3/parallax/jarallax.css">
    <input name="animation" type="hidden">
    <div id="scrollToTop" class="scrollToTop mbr-arrow-up d-none"><a style="text-align: center;"><i class="mbr-arrow-up-icon mbr-arrow-up-icon-cm cm-icon cm-icon-smallarrow-up"></i></a></div>

</body>

</html>
