<nav id="sidebar" class="">
            <div class="sidebar-header">
                <a href="index.html"><img class="main-logo" src="assets1/img/logo/certo.gif" alt=""></a>
                    <img src="assets1/img/logo/certo.gif" alt="">
            </div>
			<div class="nalika-profile">
				<div class="profile-dtl">
                <a href="/"><img class="" src="assets/img/logo/certo.gif" width="40" alt="NEGO"> NEGO <span class="lite text-info">SMS</span></a>
					<h2>Lakian <span class="min-dtn">Das</span></h2>
				</div>
				<div class="profile-social-dtl">
					<ul class="dtl-social">
						<li><a href="#"><i class="icon nalika-facebook"></i></a></li>
						<li><a href="#"><i class="icon nalika-twitter"></i></a></li>
						<li><a href="#"><i class="icon nalika-linkedin"></i></a></li>
					</ul>
				</div>
			</div>
            <div class="left-custom-menu-adp-wrap comment-scrollbar mCustomScrollbar _mCS_4 mCS-autoHide mCS_no_scrollbar" style="position: relative; overflow: visible;"><div id="mCSB_4" class="mCustomScrollBox mCS-light-1 mCSB_vertical"><div id="mCSB_4_container" class="mCSB_container" style="position:relative; top:0; left:0;" dir="ltr">
            <nav class="sidebar-nav left-sidebar-menu-pro">
                    <ul class="metismenu" id="menu1">
                        <li class="active">
                            <a class="" href="/">
								   <i class="icon nalika-home icon-wrap"></i>
								   <span class="mini-click-non">Início</span>
								</a>
                        </li>

                        <li>
                            <a class="has-arrow" href="" aria-expanded="false"><i class="icon nalika-mail icon-wrap"></i> <span class="mini-click-non">Enviar Sms</span></a>
                            <ul class="submenu-angle collapse" aria-expanded="false">
                                <li><a title="Inbox" href="#"><span class="mini-sub-pro" data-bs-toggle="modal" data-bs-target="#envio_individoulModal" data-bs-whatever="@mdo">Individual</span></a></li>
                                <li><a title="View Mail" href="#" data-bs-toggle="modal" data-bs-target="#envio_em_grupoModal" data-bs-whatever="@mdo"><span class="mini-sub-pro">Em Grupos</span></a></li>
                                <li><a title="Compose Mail" href="#" data-bs-toggle="modal" data-bs-target="#envio_em_massaModal" data-bs-whatever="@mdo"><span class="mini-sub-pro">Em Massa</span></a></li>
                            </ul>
                        </li>

                        <li>
                            <a class="has-arrow" href="#" aria-expanded="false" onclick="fazerRequisicao('/operacao_solicitar_sms?thoken=KEssE0Yz8Npj9Y8y0Rgd75Q4jt8=','corpo_principal')"><i class="icon nalika-pie-chart icon-wrap"></i> <span class="mini-click-non">Comprar Sms</span></a>
                        </li>



                        <li>

                            <a class="has-arrow" href="#" aria-expanded="false" onclick="fazerRequisicao('/operacao_grupo?thoken=KEssE0Yz8Npj9Y8y0Rgd75Q4jt8=','corpo_principal')"> <i class="icon nalika-diamond icon-wrap"></i> <span class="mini-click-non">Meus Grupos</span></a>
                            <ul class="submenu-angle collapse" aria-expanded="false">
                               

                            </ul>
                        </li>
                        <li>
                            <a class="has-arrow" href="#" aria-expanded="false" onclick="fazerRequisicao('/operacao_contacto?thoken=KEssE0Yz8Npj9Y8y0Rgd75Q4jt8=','corpo_principal')"><i class="icon nalika-pie-chart icon-wrap"></i> <span class="mini-click-non">Meus Contactos</span></a>
                            <ul class="submenu-angle collapse" aria-expanded="false">

                            </ul>
                        </li>
                        <li>
                        <a class="has-arrow" href="#" aria-expanded="false" tabindex="0" role="button" data-bs-toggle="popover" data-bs-trigger="focus" title="O que é um Sender ID ?" data-bs-content="O sender ID é nome do remetente de uma mensagem padão(Onde os seus destinatários receberam), Ex: QUIANNI, AJEC, nego.ao, MARKETING" onclick="fazerRequisicao('/operacao_sender?thoken=KEssE0Yz8Npj9Y8y0Rgd75Q4jt8=','corpo_principal')"><i class="icon nalika-table icon-wrap"></i> <span class="mini-click-non">Personalizar Nomes</span></a>
                            <ul class="submenu-angle collapse" aria-expanded="false">
                            </ul>
                        </li>

                      

                        <li>
                            <a class="has-arrow" href="#" aria-expanded="false" onclick="fazerRequisicao('/ver_notificacao?thoken=KEssE0Yz8Npj9Y8y0Rgd75Q4jt8=','corpo_principal')"><i class="icon nalika-table icon-wrap"></i> <span class="mini-click-non">Notificações</span></a>
                            <ul class="submenu-angle collapse" aria-expanded="false">
                                
                            </ul>
                        </li>
                        <li>
                        
                            <a class="has-arrow" href="#" aria-expanded="false" onclick="fazerRequisicao('/programa_afilhados?thoken=KEssE0Yz8Npj9Y8y0Rgd75Q4jt8=','corpo_principal')"><i class="icon nalika-forms icon-wrap"></i> <span class="mini-click-non">Dinheiro Online</span></a>
                            <ul class="submenu-angle collapse" aria-expanded="false">
                                
                            </ul>
                        </li>
                        <li>
                            <a class="has-arrow" href="#" aria-expanded="false" onclick="fazerRequisicao('/operacao_registro_sms?thoken=KEssE0Yz8Npj9Y8y0Rgd75Q4jt8=','corpo_principal')"> <i class="icon nalika-smartphone-call icon-wrap"></i> <span class="mini-click-non">Histórico de Envio</span></a>
                            
                        </li>
                        <li>
                            <a class="has-arrow" href="#" aria-expanded="false" onclick="fazerRequisicao('/operacao_ajuda?thoken=KEssE0Yz8Npj9Y8y0Rgd75Q4jt8=','corpo_principal')"> <i class="lar la-life-ring"></i> <span class="mini-click-non">Ajuda</span> </a>
                            
                        </li>
                    </ul>
                </nav>
            </div></div></div>
        </nav>